# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'Masonry', '1.1.0'
  pod 'Bugly', '2.5.0'
  pod 'KVOController', '1.2.0'
  pod 'Toast', '~> 4.0.0'
  pod 'Mantle', '2.1.0'
  pod 'AgoraRtcEngine_iOS', '~> 3.0.0'
  # Pods for OpenLive

end
