# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautifyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeautifyExample

  target 'BeautifyExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

   pod 'BytedEffectSDK', :path => './'
   pod 'AgoraRtcEngine_iOS', '4.0.0-rc.1'
   pod 'SSZipArchive'
   
end
